### ISSUE TITLE
JitPack.io doesn't show any commits for a particular repo

### ISSUE THREAD

**Issue by tommyettinger** [jitpack/jitpack.io#4411]
**Describe the bug**
When I go to JitPack.io and enter the URL of my repo, https://github.com/yellowstonegames/SquidSquad , I expect to see the list of commits when I go to the commit tab. Instead, only -SNAPSHOT is available, and it doesn't seem to remember those builds in the Builds tab. I can manually look up the 10-character hash substring and depend on that, but for this particular repo, the commits don't ever load.

**To Reproduce**
1. Go to 'https://jitpack.io/'
2. Enter `https://github.com/yellowstonegames/SquidSquad` in the Git repo url field
3. Check the commits tab
4. No commits are listed

**Expected behavior**
I'd expect the commits to be shown like any other repo.

**Screenshots**
![](https://i.imgur.com/nJQrLGL.png)

**Additional context**
I wonder if this is related to SquidSquad using `main` as the name of its primary branch, where most of my other repos use `master`. Also, I have a jitpack.yml file that I think is correct now, but wasn't earlier (it used openjdk15 as a normal JDK version, which apparently JitPack doesn't support yet). I don't think that should continue to affect future commits, though. The contents of that jitpack.yml file currently:
```
before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - source install-jdk.sh --feature 15
```

Thank you for your time!

**Comment by tommyettinger** [comment]
My jitpack.yml file is now:
```yaml
before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - source install-jdk.sh --feature 15
install:
  - echo "Installing with Gradle"
  - chmod 755 gradlew
  - ./gradlew clean install
```

I still can't see any commits on JitPack, even though other repos of mine also use these jitpack.yml contents without issue.
