### ISSUE TITLE
Basic commands are misisng: `rm`, `date`, `hostname` etc

### ISSUE THREAD

**Issue by diederikMrAwesome** [jitpack/jitpack.io#5049]
I'm having some issues running the build, and the logs report that basic commands ae missing.

- Link to build log from https://jitpack.io
https://jitpack.io/com/github/skynamo/flutter/jitpack-build-v0.0.12-g8fbd0fe-5/build.log

- Does the project build on your machine with **the same** commands (e.g. ./gradlew install) ?
Yep 

- What error are you seeing?
Lots of basic commands seem missing...  snippet from log:

```
Build starting...
/script/buildit.sh: line 3: date: command not found
/script/buildit.sh: line 3: hostname: command not found
Start:
Git:
/script/buildit.sh: line 5: git: command not found
/script/buildit.sh: line 6: git: command not found
/script/buildit.sh: line 6: head: command not found
/script/buildit.sh: line 6: cut: command not found

/script/buildit.sh: line 11: rm: command not found
/script/buildit.sh: line 12: cp: command not found
```

My `.jitpack.yml` file (in root of repo)

```
jdk:
  - openjdk8
before_install:
  - rm -rf HOME_DIR/.gradle/caches
  - ./tools/prepareJitpackEnvironment.sh  
  - flutter build aar
  - git fetch --tags
install:
  - cd tools && ./patch.sh && cd ..
  - cd .android/ && ./gradlew -b Flutter/build.gradle publishToMavenLocal
env:
  FLUTTER_HOME: "/opt/flutter"
  FLUTTER_ROOT: "$FLUTTER_HOME"
  PATH: "$PATH:${FLUTTER_HOME}/bin:${FLUTTER_HOME}/bin/cache/dart-sdk/bin"
```

Any help would be appreciated.

Thank you!
