### ISSUE TITLE
e: /home/jitpack/build/startup/build.gradle.kts:47:13: Expecting an element

### ISSUE THREAD

**Issue by storytellerF** [jitpack/jitpack.io#5572]
Please provide:

- https://jitpack.io/com/github/storytellerF/Bao/1.2/build.log

- build success on my machine by `gradlew build`

- >e: /home/jitpack/build/startup/build.gradle.kts:47:13: Expecting an element.

  but in my startup/build.gradle.kts， there is no line 47. Max line is 45.

Thank you!

**Comment by storytellerF** [comment]
problem solved. 
```yml
jdk:
 - openjdk8
before_install:
 - yes | sdkmanager "cmake;3.18.1"
 - sdk install java 17.0.5-oracle
 - sdk use java 17.0.5-oracle
```
