### ISSUE TITLE
Mindustry-Graaljs/v1.1.0 build

### ISSUE THREAD

**Issue by EmmmM9O** [jitpack/jitpack.io#5719]
- In https://jitpack.io/com/gitee/novarc/Mindustry-Graaljs/v1.1.0/build.log
- The Project https://github.com/EmmmM9O/Mindustry-Graaljs/
- the jitpack.yml like
```yml
jdk:
    - openjdk17
install:
    - ./gradlew wrapper
    - echo "Building..."
    - ./gradlew jar
```
Could not write standard input to Gradle build daemon.
Unable to start the daemon process.
